#!/bin/bash
# Copyright 2016-2018 See AUTHORS file
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

PACKAGES=()
bin=$1

. /sbin/sabayondevkit-functions.sh

[ -z "$bin" ] && die "No Arg given"

# Getting linked libraries
for i in $(ldd $1 | cut -d \( -f1 | cut -d \> -f2 | grep "/" | xargs echo)
do
  package=$(equo q belongs -q $i)
  [ -z "$package" ] && die "borked: $i"
  PACKAGES+=($package)
done

# Unique and ordered
U_PACKAGES=$(echo "${PACKAGES[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' ')

if [ "${#PACKAGES}" -ne 0 ]; then
	for i in ${U_PACKAGES[@]}
	do
	  echo " $i"
	done
fi
