#!/bin/bash
set -e
ROOT="${ROOT:-$PWD}"
DOCKER_IMAGE="${DOCKER_IMAGE:-sabayon/builder-amd64}"
. /sbin/sabayondevkit-functions.sh

if [ $# -eq 0 ]
  then
   echo "No arguments supplied, at least you should provide some package you wish to compile. e.g. $0 app-text/tree"
   exit 1
fi

check_docker_requirements

docker run --rm -v "$ROOT"/portage_artifacts:/usr/portage/packages -ti $DOCKER_IMAGE $@
